{"name": "test_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_allure.Test_Allure object at 0x0000000004341EB8>\n\n    @allure.step(title=\"第二个测试用例\")\n    def test_002(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_allure.py:18: AssertionError"}, "steps": [{"name": "第二个测试用例", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0\n", "trace": "  File \"d:\\programdata\\anaconda3\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"D:\\PycharmProjects\\Test_App\\Test_Allure\\scripts\\test_allure.py\", line 18, in test_002\n    assert 0\n"}, "start": 1570541851713, "stop": 1570541851714}], "start": 1570541851712, "stop": 1570541851715, "uuid": "8cef9e20-7737-4272-a34c-d322b5cc33f6", "historyId": "0c5096ad7b606625be19f770e9367822", "testCaseId": "e94fe13771c546197ed21a85382d1e57", "fullName": "scripts.test_allure.Test_Allure#test_002", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "Test_Allure"}, {"name": "host", "value": "DXIT-2018"}, {"name": "thread", "value": "11376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_allure"}]}